### ISSUE TITLE
Fails in webworker tests

### ISSUE THREAD

**Issue by victorb** [multiformats/js-multihashing#23]
Currently getting this error for webworker tests on all OSes:

```
  4) multihashing cuts the length:

     TypeError: crypto.createHash is not a function

    at Object.gsha2256 (webpack:///src/index.js:51:0 <- test/index.spec.js:13107:17)

    at Function.mh.createHash (webpack:///src/index.js:34:0 <- test/index.spec.js:13090:28)

    at Function.mh.digest (webpack:///src/index.js:19:0 <- test/index.spec.js:13075:19)

    at Multihashing (webpack:///src/index.js:12:0 <- test/index.spec.js:13068:30)

    at Context.it (webpack:///test/index.spec.js:72:0 <- test/index.spec.js:31490:7)

```

Example run: https://ci.ipfs.team/blue/organizations/jenkins/Multiformats%2Fjs-multihashing/detail/master/3/pipeline/21

**Comment by dryajov** [comment]
Hmm.. don't seem like this been ported over to the new aegir. I'll port it real quick.

**Comment by dryajov** [comment]
Being handled in - https://github.com/multiformats/js-multihashing/pull/19

**Comment by daviddias** [comment]
thanks @dryajov @VictorBjelkholm :)
